### ISSUE TITLE
no module named 'pd_utils.xxxx'

### ISSUE THREAD

**Issue by jcalcada** [Preocts/pd-utils#105]
I'm trying to install this on Windows and the command "python -m pd_utils.coverage-gap-report" returns a "no module named 'pd_utils.coverage-gap-report'. 

I'm running the latest python3 (just installed it today) and ran a pip install pd_utils (a couple of warnings but no errors). I've downloaded your repo and am in the pd-utils-main directory when I try to run it. 

Any ideas ?

**Comment by Preocts** [comment]
You'll want to use the following: 

`pd-utils coverage-gap-report` 

Alternatively, if the entry script `pd-utils` is not working, you can replace it and call the command line entry handler directly:

`python -m pd_utils.cli.handler coverage-gap-report`

```console
$ pd-utils coverage-gap-report --help
usage: pd-utils coverage-gap-report [-h] [--look-ahead LOOK_AHEAD] [--token TOKEN] [--email EMAIL] [--logging-level {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [--timeout TIMEOUT]

options:
  -h, --help            show this help message and exit
  --look-ahead LOOK_AHEAD
                        Number of days to look ahead for coverage gaps.
  --token TOKEN         PagerDuty API Token (default: $PAGERDUTY_TOKEN)
  --email EMAIL         PagerDuty Email (default: $PAGERDUTY_EMAIL)
  --logging-level {DEBUG,INFO,WARNING,ERROR,CRITICAL}
                        Logging level (default: $LOGGING_LEVEL | ERROR)
  --timeout TIMEOUT     Timeout seconds for HTTP calls (default: 60)
```

**Comment by jcalcada** [comment]
Thanks!
