### ISSUE TITLE
Pull users lists

### ISSUE THREAD

**Issue by Preocts** [Preocts/pd-utils#6]
Export CSV has been removed from the Users window. (why?)  Build report to export:

- Name
- Email
- Base Permission
- ???

**Comment by dmcclure-pdt** [comment]
A few other things commonly asked for are:

**Comment by Preocts** [comment]
v1 late night pondering

columns:
- name
- html_url
- email
- title
- base role
- list of teams (TeamName (role)
- has email (yes | no | blocked)
- has phone (yes | no | blocked)
- has sms (yes | no | blocked)
- has mobile (yes | no | blocked)
- high urgency email noti (None | [N minutes, ...])
- high urgency sms noti (None | [N minutes])
- high urgency phone noti (None | [N minutes])
- high urgency mobile noti (None | [N minutes])
- low urgency email noti (None | [N minutes])
- low urgency sms noti (None | [N minutes])
- low urgency phone noti (None | [N minutes])
- low urgency mobile noti (None | [N minutes])

CLI option
`--teams=` , comma sep list of PagerDuty team IDs to isolate report to
